### ISSUE TITLE
Remove babel-preset-stage-2 

### ISSUE THREAD

**Issue by epeden** [codejamninja/idempotent-babel-polyfill#1]
babel-preset-stage-2 is not needed and can be removed. Because of the babel config in the package.json, we have to include babel-preset-stage-2 as a devDependency in our project when using idempotent-babel-polyfill, which we would prefer to not do. I removed babel-preset-stage-2 from the devDependencies and the babel config in package.json and tested and it doesn't appear to be needed.

**Comment by clayrisser** [comment]
Ok, thanks. I'll fix that.

**Comment by clayrisser** [comment]
Ok, it's fixed. Update to version `6.26.0-1`.
