### ISSUE TITLE
New `@babel/polyfill` package using Babel 7 (embedded noConflict mode)

### ISSUE THREAD

**Issue by yvele** [codejamninja/idempotent-babel-polyfill#2]
Babel polyfill package changed his name from `babel-polyfill` to `@babel/polyfill`.

Also note that `@babel/polyfill` has a new `noConflict` mode as described here
 - https://github.com/babel/babel/issues/4019
 - https://github.com/babel/babel/pull/6371
 - https://github.com/babel/babel/pull/6371/files

```js
import "@babel/polyfill/noConflict";
```

Should this package include a deprecation notice? Or update itself with `@babel/polyfill`?

**Comment by clayrisser** [comment]
I should update it to add support for `@babel/polyfill`. I won't deprecate it, but I will probably recommend a different approach for new projects. However, the idempotent way should still be supported.

Thanks for filling this issue. I've been meaning to get around to this and haven't had the motivation. Someone filing an issue usually is enough motivation.

**Comment by clayrisser** [comment]
I finally got around to releasing a compatible version 7, mainly to give platforms already using this module backward compatibility with babel 7.

https://github.com/codejamninja/idempotent-babel-polyfill/releases/tag/7.0.0
https://www.npmjs.com/package/idempotent-babel-polyfill/v/7.0.0
